//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientIntranet.ServiceTigli {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTigli.ITigliService")]
    public interface ITigliService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITigliService/GetItinerary", ReplyAction="http://tempuri.org/ITigliService/GetItineraryResponse")]
        string GetItinerary(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITigliService/GetItinerary", ReplyAction="http://tempuri.org/ITigliService/GetItineraryResponse")]
        System.Threading.Tasks.Task<string> GetItineraryAsync(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITigliService/GetCoords", ReplyAction="http://tempuri.org/ITigliService/GetCoordsResponse")]
        string GetCoords(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITigliService/GetCoords", ReplyAction="http://tempuri.org/ITigliService/GetCoordsResponse")]
        System.Threading.Tasks.Task<string> GetCoordsAsync(string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITigliServiceChannel : ClientIntranet.ServiceTigli.ITigliService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TigliServiceClient : System.ServiceModel.ClientBase<ClientIntranet.ServiceTigli.ITigliService>, ClientIntranet.ServiceTigli.ITigliService {
        
        public TigliServiceClient() {
        }
        
        public TigliServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TigliServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TigliServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TigliServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetItinerary(string origin, string destination) {
            return base.Channel.GetItinerary(origin, destination);
        }
        
        public System.Threading.Tasks.Task<string> GetItineraryAsync(string origin, string destination) {
            return base.Channel.GetItineraryAsync(origin, destination);
        }
        
        public string GetCoords(string address) {
            return base.Channel.GetCoords(address);
        }
        
        public System.Threading.Tasks.Task<string> GetCoordsAsync(string address) {
            return base.Channel.GetCoordsAsync(address);
        }
    }
}
