//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTigli.ServiceTigli {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTigli.ITigliService")]
    public interface ITigliService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITigliService/echoget", ReplyAction="http://tempuri.org/ITigliService/echogetResponse")]
        string echoget(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITigliService/echoget", ReplyAction="http://tempuri.org/ITigliService/echogetResponse")]
        System.Threading.Tasks.Task<string> echogetAsync(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITigliService/getCoords", ReplyAction="http://tempuri.org/ITigliService/getCoordsResponse")]
        string getCoords(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITigliService/getCoords", ReplyAction="http://tempuri.org/ITigliService/getCoordsResponse")]
        System.Threading.Tasks.Task<string> getCoordsAsync(string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITigliServiceChannel : ClientTigli.ServiceTigli.ITigliService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TigliServiceClient : System.ServiceModel.ClientBase<ClientTigli.ServiceTigli.ITigliService>, ClientTigli.ServiceTigli.ITigliService {
        
        public TigliServiceClient() {
        }
        
        public TigliServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TigliServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TigliServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TigliServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string echoget(string origin, string destination) {
            return base.Channel.echoget(origin, destination);
        }
        
        public System.Threading.Tasks.Task<string> echogetAsync(string origin, string destination) {
            return base.Channel.echogetAsync(origin, destination);
        }
        
        public string getCoords(string address) {
            return base.Channel.getCoords(address);
        }
        
        public System.Threading.Tasks.Task<string> getCoordsAsync(string address) {
            return base.Channel.getCoordsAsync(address);
        }
    }
}
